version: 2

models:
    - name: stg_orders
      columns: 
          - name: order_id
            tests:
             - unique
             - not_null
    - name: customers
      columns:
          - name: customer_id
            tests:
             - unique
             - not_null
    - name: payments
      columns:
          - name: payment_id
            tests:
             - unique